export const listCategories = [
  'Smartphones',
  'Laptops',
  'Tablets',
  'Headphones',
  'Bluetooth Speakers',
  'Smartwatches',
  'Cameras',
  'DSLR Cameras',
  'Camera Lenses',
  'Camcorders',
  'Televisions',
  'Computer Monitors',
  'Projectors',
  'Gaming Consoles',
  'Keyboards',
  'Computer Mice',
  'Printers',
  'Scanners',
  'External Hard Drives',
  'USB Flash Drives',
  'Memory Cards',
  'Power Banks',
  'Charging Cables',
  'Charger Adapters',
  'Phone Cases',
  'Screen Protectors',
  'Phone Stands',
  'Refrigerators',
  'Washing Machines',
  'Clothes Dryers',
  'Dishwashers',
  'Microwave Ovens',
  'Ovens',
  'Rice Cookers',
  'Electric Stoves',
  'Gas Stoves',
  'Vacuum Cleaners',
  'Electric Fans',
  'Air Purifiers',
  'Air Conditioners',
  'Heaters',
  'Dehumidifiers',
  'Water Dispensers',
  'Coffee Makers',
  'Blenders',
  'Food Processors',
  'Juicers',
  'Toasters',
  'Electric Kettles',
  'Slow Cookers',
  'Pressure Cookers',
  'Air Fryers',
  'Grills',
  'Food Dehydrators',
  'Ice Cream Makers',
  'Bread Makers',
  'Waffle Makers',
  'Electric Skillets',
  'Hand Mixers',
  'Stand Mixers',
  'Espresso Machines',
  'Wine Coolers',
  'Trash Compactors',
  'Garbage Disposals',
  'Range Hoods',
  'Ceiling Fans',
  'Light Bulbs',
  'Lamps',
  'Chandeliers',
  'Wall Sconces',
  'Outdoor Lighting',
  'Smart Home Devices',
  'Thermostats',
  'Smoke Detectors',
  'Carbon Monoxide Detectors',
  'Security Cameras',
  'Doorbells',
  'Smart Locks',
  'Robot Vacuums',
  'Lawn Mowers',
  'Trimmers',
  'Leaf Blowers',
  'Pressure Washers',
  'Snow Blowers',
  'Garden Hoses',
  'Sprinklers',
  'Gardening Tools',
  'Power Tools',
  'Hand Tools',
  'Tool Storage',
  'Ladders',
  'Generators',
  'Solar Panels',
  'Batteries',
  'Extension Cords',
  'Surge Protectors',
  'Furniture',
  'Sofas',
  'Chairs',
  'Tables',
  'Beds',
  'Mattresses',
  'Dressers',
  'Nightstands',
  'Bookcases',
  'Desks',
  'Office Chairs',
  'Filing Cabinets',
  'Ottomans',
  'Bean Bags',
  'Patio Furniture',
  'Outdoor Umbrellas',
  'Hammocks',
  'Rugs',
  'Carpets',
  'Curtains',
  'Blinds',
  'Pillows',
  'Blankets',
  'Bedding Sets',
  'Towels',
  'Shower Curtains',
  'Bathroom Accessories',
  'Kitchen Utensils',
  'Cookware',
  'Bakeware',
  'Dinnerware',
  'Flatware',
  'Glassware',
  'Food Storage Containers',
  'Lunch Boxes',
  'Water Bottles',
  'Thermoses',
  'Cutting Boards',
  'Knife Sets',
  'Measuring Cups',
  'Kitchen Scales',
  'Aprons',
  'Oven Mitts',
  'Dish Racks',
  'Trash Cans',
  'Cleaning Supplies',
  'Laundry Baskets',
  'Ironing Boards',
  'Clothes Hangers',
  'Storage Boxes',
  'Shoe Racks',
  'Coat Racks',
  'Mirrors',
  'Picture Frames',
  'Wall Art',
  'Clocks',
  'Vases',
  'Candles',
  'Artificial Plants',
  'Plant Pots',
  'Books',
  'Magazines',
  'Newspapers',
  'Stationery',
  'Notebooks',
  'Pens',
  'Pencils',
  'Markers',
  'Highlighters',
  'Sticky Notes',
  'Calendars',
  'Planners',
  'Calculators',
  'Printers',
  'Scanners',
  'Shredders',
  'Staplers',
  'Hole Punches',
  'Paper Clips',
  'Binders',
  'Folders',
  'Envelopes',
  'Shipping Supplies',
  'Clothing',
  'Shoes',
  'Accessories',
  'Jewelry',
  'Watches',
  'Handbags',
  'Wallets',
  'Backpacks',
  'Luggage',
  'Travel Accessories',
  'Sunglasses',
  'Hats',
  'Scarves',
  'Gloves',
  'Socks',
  'Underwear',
  'Sleepwear',
  'Activewear',
  'Swimwear',
  'Outerwear',
  'Formal Wear',
  'Costumes',
  'Uniforms',
  'Baby Clothing',
  'Childrens Clothing',
  'Maternity Clothing',
  'Plus Size Clothing',
  'Pet Supplies',
  'Dog Food',
  'Cat Food',
  'Pet Toys',
  'Pet Beds',
  'Pet Carriers',
  'Pet Grooming Supplies',
  'Pet Medications',
  'Aquariums',
  'Bird Cages',
  'Pet Fencing',
  'Pet Doors',
  'Pet Cameras',
  'Pet Trackers',
  'Leashes',
  'Collars',
  'Pet Bowls',
  'Pet Feeders',
  'Litter Boxes',
  'Pet Waste Bags',
  'Pet Stain Removers',
  'Pet Hair Removers',
  'Pet Shampoos',
  'Pet Nail Clippers',
  'Pet Dental Care',
  'Pet First Aid Kits',
  'Pet Vitamins',
  'Pet Treats',
  'Pet Training Aids',
  'Pet Clothing',
  'Pet Costumes',
  'Pet Life Jackets',
  'Pet Car Seats',
  'Pet Strollers',
  'Pet Ramps',
  'Pet Steps',
  'Pet Gates',
  'Pet Playpens',
  'Pet Agility Equipment',
  'Pet Travel Bags',
  'Sports Equipment',
  'Fitness Equipment',
  'Yoga Mats',
  'Dumbbells',
  'Barbells',
  'Weight Benches',
  'Treadmills',
  'Exercise Bikes',
  'Elliptical Machines',
  'Rowing Machines',
  'Resistance Bands',
  'Jump Ropes',
  'Exercise Balls',
  'Foam Rollers',
  'Fitness Trackers',
  'Heart Rate Monitors',
  'Gym Bags',
  'Water Bottles',
  'Protein Shakers',
  'Sports Jerseys',
  'Team Merchandise',
  'Bicycles',
  'Bike Accessories',
  'Skateboards',
  'Roller Skates',
  'Inline Skates',
  'Scooters',
  'Helmets',
  'Protective Gear',
  'Camping Gear',
  'Hiking Gear',
  'Fishing Equipment',
  'Hunting Equipment',
  'Golf Clubs',
  'Tennis Rackets',
  'Basketballs',
  'Footballs',
  'Soccer Balls',
  'Baseballs',
  'Softballs',
  'Volleyballs',
  'Table Tennis Equipment',
  'Badminton Equipment',
  'Swimming Goggles',
  'Swim Caps',
  'Life Jackets',
  'Surfboards',
  'Paddleboards',
  'Kayaks',
  'Canoes',
  'Snowboards',
  'Skis',
  'Ice Skates',
  'Sleds',
  'Snow Tubes',
  'Climbing Gear',
  'Martial Arts Equipment',
  'Boxing Equipment',
  'Gymnastics Equipment',
  'Dance Equipment',
  'Cheerleading Equipment',
  'Archery Equipment',
  'Darts',
  'Billiards Equipment',
  'Foosball Tables',
  'Air Hockey Tables',
  'Ping Pong Tables',
  'Board Games',
  'Card Games',
  'Puzzles',
  'Video Games',
  'Gaming Accessories',
  'Virtual Reality Headsets',
  'Drones',
  'Remote Control Toys',
  'Action Figures',
  'Dolls',
  'Building Blocks',
  'Educational Toys',
  'Arts and Crafts Supplies',
  'Musical Instruments',
  'Music Accessories',
  'Sheet Music',
  'DJ Equipment',
  'Audio Equipment',
  'Microphones',
  'Speakers',
  'Amplifiers',
  'Mixers',
  'Turntables',
  'Record Players',
  'Vinyl Records',
  'CDs',
  'DVDs',
  'Blu-ray Discs',
  'Streaming Devices',
  'E-readers',
  'Digital Cameras',
  'Film Cameras',
  'Camera Accessories',
  'Binoculars',
  'Telescopes',
  'Microscopes',
  'Weather Instruments',
  'Compasses',
  'GPS Devices',
  'Maps',
  'Globes',
  'Antiques',
  'Collectibles',
  'Artwork',
  'Sculptures',
  'Posters',
  'Prints',
  'Stamps',
  'Coins',
  'Comic Books',
  'Trading Cards',
  'Model Kits',
  'Costumes',
  'Party Supplies',
  'Gift Wrapping Supplies',
  'Greeting Cards',
  'Invitations',
  'Gift Cards',
  'Promotional Items',
  'Personalized Gifts',
  'Religious Items',
  'Seasonal Decorations',
  'Holiday Ornaments',
  'Artificial Christmas Trees',
  'Halloween Decorations',
  'Easter Decorations',
  'Wedding Supplies',
  'Baby Shower Supplies',
  'Graduation Supplies',
  'Anniversary Gifts',
  'Birthday Gifts',
  'Gag Gifts',
  'Novelty Items',
  'Incense and Oils',
  'Aromatherapy Products',
  'Massage Equipment',
  'Acupuncture Supplies',
  'First Aid Kits',
  'Medical Supplies',
  'Mobility Aids',
  'Orthopedic Supports',
  'Vitamins and Supplements',
  'Herbal Remedies',
  'Weight Loss Products',
  'Personal Care Products',
  'Skincare Products',
  'Haircare Products',
  'Makeup',
  'Fragrances',
  'Oral Care Products',
  'Shaving Supplies',
  'Hair Removal Products',
  'Feminine Hygiene Products',
  'Mens Grooming Products',
  'Nail Care Products',
  'Sun Care Products',
  'Bath and Body Products',
  'Massage Oils',
  'Essential Oils',
  'Diffusers',
  'Hair Styling Tools',
  'Mirrors',
  'Scales',
  'Bathroom Accessories',
  'Shower Heads',
  'Toilet Paper',
  'Paper Towels',
  'Tissues',
  'Soap Dispensers',
  'Toothbrush Holders',
  'Shower Caddies',
  'Bathroom Organizers',
  'Laundry Detergent',
  'Fabric Softener',
  'Dryer Sheets',
  'Stain Removers',
  'Bleach',
  'All-Purpose Cleaners',
  'Glass Cleaners',
  'Floor Cleaners',
  'Dishwashing Liquid',
  'Dishwasher Detergent',
  'Sponges',
  'Scrub Brushes',
  'Mops',
  'Brooms',
  'Dustpans',
  'Dusters',
  'Trash Bags',
  'Recycling Bins',
  'Compost Bins',
  'Storage Containers',
  'Food Storage Bags',
  'Aluminum Foil',
  'Plastic Wrap',
  'Wax Paper',
  'Paper Plates',
  'Plastic Utensils',
  'Napkins',
  'Straws',
  'Coffee Filters',
  'Tea Bags',
  'Spices and Seasonings',
  'Condiments',
  'Sauces',
  'Cooking Oils',
  'Vinegars',
  'Baking Supplies',
  'Pasta',
  'Rice',
  'Grains',
  'Canned Goods',
  'Snack Foods',
  'Breakfast Cereals',
  'Frozen Foods',
  'Dairy Products',
  'Meat and Poultry',
  'Seafood',
  'Fresh Produce',
  'Bread and Bakery Items',
  'Beverages',
  'Alcoholic Beverages',
  'Tobacco Products',
  'Vaping Products',
  'Pet Food',
  'Baby Food',
  'Infant Formula',
  'Diapers',
  'Baby Wipes',
  'Baby Care Products',
  'Cribs',
  'Car Seats',
  'Strollers',
  'High Chairs',
  'Baby Monitors',
  'Baby Toys',
  'Children Books',
  'School Supplies',
  'Backpacks',
  'Lunch Boxes',
  'Educational Materials',
  'Art Supplies',
  'Craft Supplies',
  'Sewing Supplies',
  'Knitting Supplies',
  'Scrapbooking Supplies',
  'Home Improvement Tools',
  'Plumbing Supplies',
  'Electrical Supplies',
  'HVAC Supplies',
  'Painting Supplies',
  'Wallpaper',
  'Flooring',
  'Tiles',
  'Lumber',
  'Hardware',
  'Doors',
  'Windows',
  'Roofing Materials',
  'Insulation',
  'Siding',
  'Gutters',
  'Fencing',
  'Decking',
  'Patio Pavers',
  'Landscaping Supplies',
  'Garden Soil',
  'Fertilizers',
  'Pesticides',
  'Seeds',
  'Plants',
  'Trees',
  'Shrubs',
  'Lawn Care Equipment',
  'Outdoor Power Equipment',
  'Pool Supplies',
  'Hot Tub Supplies',
  'Sauna Equipment',
  'Outdoor Kitchens',
  'Outdoor Heaters',
  'Fire Pits',
  'Outdoor Lighting',
  'Garage Door Openers',
  'Safes',
  'Home Security Systems',
  'Smoke Detectors',
  'Carbon Monoxide Detectors',
  'Fire Extinguishers',
  'First Aid Kits',
  'Emergency Preparedness Kits',
  'Flashlights',
  'Batteries',
  'Solar Panels',
  'Wind Turbines',
  'Energy Storage Systems',
  'Water Filtration Systems',
  'Water Softeners',
  'Water Heaters',
  'Sump Pumps',
  'Septic System Supplies',
  'Plumbing Fixtures',
  'Faucets',
  'Showerheads',
  'Toilets',
  'Bathtubs',
  'Sinks',
  'Vanities',
  'Mirrors',
  'Medicine Cabinets',
  'Light Fixtures',
  'Ceiling Fans',
  'Electrical Panels',
  'Circuit Breakers',
  'Outlets',
  'Switches',
  'Dimmers',
  'Smart Home Devices',
  'Thermostats',
  'HVAC Systems',
  'Air Filters',
  'Humidifiers',
  'Dehumidifiers',
  'Air Purifiers',
  'Vacuum Cleaners',
  'Steam Cleaners',
  'Carpet Cleaners',
  'Pressure Washers',
  'Window Cleaning Supplies',
  'Cleaning Chemicals',
  'Trash Compactors',
  'Recycling Bins',
  'Composting Supplies',
  'Pest Control Products',
  'Moving Supplies',
  'Storage Containers',
  'Shelving Units',
  'Closet Organizers',
  'Garage Organization Systems',
  'Laundry Room Organizers',
  'Office Furniture',
  'Home Office Equipment',
  'Printers',
  'Scanners',
  'Shredders',
  'Laminators',
  'Binding Machines',
  'Office Supplies',
  'Writing Instruments',
  'Paper Products',
  'Notebooks',
  'Calendars',
  'Planners',
  'File Cabinets',
  'Safes',
  'Cash Registers',
  'Point of Sale Systems',
  'Time Clocks',
  'Label Makers',
  'Barcode Scanners',
  'Credit Card Readers',
  'Surveillance Cameras',
  'Access Control Systems',
  'Locks',
  'Keys',
  'Padlocks',
  'Mailboxes',
  'Address Signs',
  'House Numbers',
  'Doorbells',
  'Door Knockers',
  'Weather Vanes',
  'Flags',
  'Flag Poles',
  'Bird Feeders',
  'Bird Baths',
  'Outdoor Fountains',
  'Garden Statues',
  'Wind Chimes',
  'Outdoor Clocks',
  'Rain Gauges',
  'Thermometers',
  'Barometers',
  'Weather Stations',
  'Telescopes',
  'Binoculars',
  'Microscopes',
  'Magnifying Glasses',
  'Compasses',
  'Maps',
  'Globes',
  'Travel Guides',
  'Language Learning Materials',
  'Musical Instruments',
  'Sheet Music',
  'Music Stands',
  'Instrument Cases',
  'Tuners',
  'Metronomes',
  'Audio Recording Equipment',
  'DJ Equipment',
  'Karaoke Machines',
  'Dance Floor Equipment',
  'Stage Lighting',
  'Fog Machines',
  'Costumes',
  'Theatrical Makeup',
  'Wigs',
  'Magic Tricks',
  'Juggling Equipment',
  'Circus Equipment',
  'Carnival Games',
  'Arcade Machines',
  'Pinball Machines',
  'Slot Machines',
  'Casino Equipment',
  'Poker Tables',
  'Playing Cards',
  'Dice',
  'Board Games',
  'Puzzles',
  'Strategy Games',
  'Role-Playing Games',
  'Miniature Wargaming Supplies',
  'Trading Card Games',
  'Collectible Figurines',
  'Model Kits',
  'Remote Control Vehicles',
  'Drones',
  'Robotics Kits',
  'Science Experiment Kits',
  'Rock Tumbling Equipment',
  'Coin Collecting Supplies',
  'Stamp Collecting Supplies',
  'Comic Book Collecting Supplies',
  'Sports Memorabilia',
  'Autograph Collections',
  'Antiques',
  'Vintage Clothing',
  'Vintage Furniture',
  'Vintage Electronics',
  'Vinyl Records',
  'Cassette Tapes',
  'CDs',
  'DVDs',
  'Blu-ray Discs',
  'VHS Tapes',
  'Film Reels',
  'Film Projection Equipment',
  'Darkroom Equipment',
  'Photographic Paper',
  'Camera Film',
  'Disposable Cameras',
  'Instant Cameras',
  'Action Cameras',
  '360-Degree Cameras',
  'Webcams',
  'Security Cameras',
  'Dash Cams',
  'Trail Cameras',
  'Underwater Cameras',
  'Camera Drones',
  'Camera Lenses',
  'Camera Filters',
  'Camera Flashes',
  'Camera Tripods',
  'Camera Bags',
  'Memory Cards',
  'External Hard Drives',
  'NAS Devices',
  'Cloud Storage Services',
  'Computer Components',
  'Graphics Cards',
  'Processors',
  'Motherboards',
  'RAM',
  'Power Supplies',
  'Computer Cases',
  'Cooling Systems',
  'Network Equipment',
  'Modems',
  'Routers',
  'Network Switches',
  'Network Attached Storage',
  'Ethernet Cables',
  'Fiber Optic Cables',
  'Wireless Access Points',
  'Antennas',
  'Satellite Dishes',
  'Cable TV Equipment',
  'Streaming Devices',
  'Media Players',
  'E-book Readers',
  'Smart Glasses',
  'Smart Rings',
  'Wearable Tech',
  'Medical Alert Systems',
  'Hearing Aids',
  'Vision Correction',
  'Mobility Aids',
  'Prosthetics',
  'Orthotics',
  'Compression Garments',
  'Therapy Equipment',
  'Massage Equipment',
  'Acupuncture Supplies',
  'Chiropractic Equipment',
  'Dental Equipment',
  'Veterinary Supplies',
  'Laboratory Equipment',
  'Scientific Instruments',
  'Industrial Equipment',
  'Manufacturing Machinery',
  'Packaging Equipment',
  'Material Handling Equipment',
  'Warehousing Supplies',
  'Shipping Supplies',
  'Office Furniture',
  'Retail Store Fixtures',
  'Restaurant Equipment',
  'Commercial Kitchen Appliances',
  'Food Service Supplies',
  'Janitorial Supplies',
  'Industrial Cleaning Equipment',
  'Waste Management Equipment',
  'Recycling Equipment',
  'Environmental Monitoring Equipment',
  'Safety Equipment',
  'Personal Protective Equipment',
  'Fire Safety Equipment',
  'Traffic Safety Equipment',
  'Construction Equipment',
  'Mining Equipment',
  'Forestry Equipment',
  'Agricultural Equipment',
  'Livestock Supplies',
  'Equestrian Equipment',
  'Beekeeping Supplies',
  'Aquaculture Equipment',
  'Hydroponics Equipment',
  'Greenhouse Supplies',
]

export const listDiscountTypes = [
  'Percentage Discount',
  'Buy One Get One',
  'Free Shipping',
  'Event Discount',
  'Flash Sale',
]
